package com.plm.attribute.version.service.workbook;

import com.plm.attribute.version.service.MetaAttributeManageService;
import com.plm.attribute.version.service.MetaAttributeQueryService;
import com.plm.attribute.version.service.MetaCategoryCrudService;
import com.plm.attribute.version.service.MetaCodeRuleService;
import com.plm.common.version.domain.MetaCodeRule;
import com.plm.common.api.dto.attribute.MetaAttributeDefDetailDto;
import com.plm.common.api.dto.attribute.MetaAttributeUpsertRequestDto;
import com.plm.common.api.dto.category.CreateCategoryRequestDto;
import com.plm.common.api.dto.code.CodeRuleSaveRequestDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportDryRunOptionsDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportDryRunResponseDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportDryRunStartResponseDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportJobStatusDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportLogEventDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportLogPageDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportPostProcessResponseDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportStartRequestDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportStartResponseDto;
import com.plm.infrastructure.version.repository.MetaCategoryDefRepository;
import com.plm.infrastructure.version.repository.MetaCodeRuleRepository;
import com.plm.infrastructure.version.repository.MetaLovDefRepository;
import com.plm.infrastructure.version.repository.MetaLovVersionRepository;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.core.task.SyncTaskExecutor;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.UUID;

@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.NONE,
        properties = {
                "spring.main.lazy-initialization=true",
                "spring.main.allow-bean-definition-overriding=true"
        }
)
@ActiveProfiles("dev")
@Transactional
@Import(WorkbookImportServiceIT.SyncAsyncExecutorConfig.class)
class WorkbookImportServiceIT {

    @Autowired
    private WorkbookImportDryRunService dryRunService;

    @Autowired
    private WorkbookImportExecutionService executionService;

    @Autowired
    private WorkbookImportDryRunJobService dryRunJobService;

    @Autowired
    private WorkbookImportRuntimeService runtimeService;

    @Autowired
    private MetaCategoryCrudService categoryCrudService;

    @Autowired
    private MetaCodeRuleService codeRuleService;

    @Autowired
    private MetaCodeRuleRepository codeRuleRepository;

    @Autowired
    private MetaAttributeManageService attributeManageService;

    @Autowired
    private MetaAttributeQueryService attributeQueryService;

    @Autowired
    private MetaCategoryDefRepository categoryDefRepository;

    @Autowired
    private MetaLovDefRepository lovDefRepository;

    @Autowired
    private MetaLovVersionRepository lovVersionRepository;

    @Test
    void dryRun_shouldPreviewAutoGeneratedCategoryAttributeAndEnumCodes() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createAutoWorkbook(suffix);

        WorkbookImportDryRunResponseDto response = dryRunService.dryRun(workbook, "it-user", autoOptions());
        WorkbookImportSupport.ImportSessionState session = runtimeService.getSession(response.getImportSessionId());

        Assertions.assertNotNull(response.getImportSessionId());
        Assertions.assertEquals(0, response.getSummary().getErrorCount());
        Assertions.assertTrue(Boolean.TRUE.equals(response.getSummary().getCanImport()));
        Assertions.assertEquals(2, response.getChangeSummary().getCategories().getCreate());
        Assertions.assertEquals(1, response.getChangeSummary().getAttributes().getCreate());
        Assertions.assertEquals(2, response.getChangeSummary().getEnumOptions().getCreate());
        Assertions.assertNotNull(session.executionPlan());
        Assertions.assertEquals(2, session.executionPlan().categories().size());
        Assertions.assertEquals(1, session.executionPlan().attributes().size());
        Assertions.assertEquals(2, session.executionPlan().enumOptions().size());
        Assertions.assertTrue(session.executionPlan().categories().get(0).shouldWrite());
        Assertions.assertNotNull(session.executionPlan().categories().get(0).newStateHash());
        Assertions.assertNull(session.executionPlan().categories().get(0).existingCategoryId());
        Assertions.assertTrue(session.executionPlan().attributes().get(0).shouldWrite());
        Assertions.assertNotNull(session.executionPlan().attributes().get(0).newStructureHash());
        Assertions.assertNull(session.executionPlan().attributes().get(0).existingAttributeId());
        Assertions.assertTrue(session.executionPlan().enumOptions().get(0).shouldWrite());
        Assertions.assertNotNull(session.executionPlan().enumOptions().get(0).newValueHash());
        Assertions.assertNull(session.executionPlan().enumOptions().get(0).existingOptionCode());
        Assertions.assertNotNull(session.expiresAt());
        Assertions.assertTrue(session.expiresAt().isAfter(session.createdAt()));

        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto root = response.getPreview().getCategories().get(0);
        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto child = response.getPreview().getCategories().get(1);
        WorkbookImportDryRunResponseDto.AttributePreviewItemDto attribute = response.getPreview().getAttributes().get(0);
        WorkbookImportDryRunResponseDto.EnumOptionPreviewItemDto firstEnum = response.getPreview().getEnumOptions().get(0);
        WorkbookImportDryRunResponseDto.EnumOptionPreviewItemDto secondEnum = response.getPreview().getEnumOptions().get(1);

        Assertions.assertEquals("SYSTEM_RULE_AUTO", root.getCodeMode());
        Assertions.assertEquals(4, root.getRowNumber());
        Assertions.assertTrue(root.getResolvedFinalCode().startsWith("MATERIAL-"), "actual root code=" + root.getResolvedFinalCode());
        Assertions.assertEquals("/" + root.getResolvedFinalCode(), root.getResolvedFinalPath());

        Assertions.assertEquals("SYSTEM_RULE_AUTO", child.getCodeMode());
        Assertions.assertEquals(root.getResolvedFinalPath() + "/" + child.getResolvedFinalCode(), child.getResolvedFinalPath());
        Assertions.assertTrue(child.getResolvedFinalCode().startsWith("MATERIAL-"), "actual child code=" + child.getResolvedFinalCode());

        Assertions.assertEquals(child.getResolvedFinalCode(), attribute.getCategoryCode());
        Assertions.assertEquals(3, attribute.getRowNumber());
        Assertions.assertEquals("SYSTEM_RULE_AUTO", attribute.getCodeMode());
        Assertions.assertTrue(attribute.getResolvedFinalCode().startsWith("ATTR-" + child.getResolvedFinalCode() + "-"),
                "actual attribute code=" + attribute.getResolvedFinalCode());

        Assertions.assertEquals(attribute.getResolvedFinalCode(), firstEnum.getAttributeKey());
        Assertions.assertEquals(attribute.getResolvedFinalCode(), secondEnum.getAttributeKey());
        Assertions.assertEquals(3, firstEnum.getRowNumber());
        Assertions.assertTrue(firstEnum.getResolvedFinalCode().startsWith("ENUM-" + attribute.getResolvedFinalCode() + "-"),
                "actual enum code=" + firstEnum.getResolvedFinalCode());
        Assertions.assertTrue(secondEnum.getResolvedFinalCode().startsWith("ENUM-" + attribute.getResolvedFinalCode() + "-"),
                "actual enum code=" + secondEnum.getResolvedFinalCode());
    }

    @Test
    void dryRun_shouldKeepDistinctAutoCodesForSiblingCategories() throws Exception {
        String suffix = uniqueSuffix();
        String rootCode = "ROOT-SIB-" + suffix;
        String childOneCode = "CHILD-A-" + suffix;
        String childTwoCode = "CHILD-B-" + suffix;
        String childThreeCode = "CHILD-C-" + suffix;
        MockMultipartFile workbook = createWorkbook(
                "workbook-auto-category-siblings-" + suffix + ".xlsx",
                List.<String[]>of(
                        new String[]{"MATERIAL", rootCode, "/" + rootCode, "Sibling Root " + suffix},
                        new String[]{"MATERIAL", childOneCode, "/" + rootCode + "/" + childOneCode, "Sibling A " + suffix},
                        new String[]{"MATERIAL", childTwoCode, "/" + rootCode + "/" + childTwoCode, "Sibling B " + suffix},
                        new String[]{"MATERIAL", childThreeCode, "/" + rootCode + "/" + childThreeCode, "Sibling C " + suffix}
                ),
                List.of(),
                List.of());

        WorkbookImportDryRunResponseDto response = dryRunService.dryRun(workbook, "it-user", autoOptions());

        Assertions.assertEquals(4, response.getPreview().getCategories().size());

        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto root = response.getPreview().getCategories().get(0);
        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto firstChild = response.getPreview().getCategories().get(1);
        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto secondChild = response.getPreview().getCategories().get(2);
        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto thirdChild = response.getPreview().getCategories().get(3);

        Assertions.assertEquals("SYSTEM_RULE_AUTO", firstChild.getCodeMode());
        Assertions.assertEquals("SYSTEM_RULE_AUTO", secondChild.getCodeMode());
        Assertions.assertEquals("SYSTEM_RULE_AUTO", thirdChild.getCodeMode());
        Assertions.assertNotEquals(firstChild.getResolvedFinalCode(), secondChild.getResolvedFinalCode());
        Assertions.assertNotEquals(firstChild.getResolvedFinalCode(), thirdChild.getResolvedFinalCode());
        Assertions.assertNotEquals(secondChild.getResolvedFinalCode(), thirdChild.getResolvedFinalCode());
        Assertions.assertEquals(root.getResolvedFinalPath() + "/" + firstChild.getResolvedFinalCode(), firstChild.getResolvedFinalPath());
        Assertions.assertEquals(root.getResolvedFinalPath() + "/" + secondChild.getResolvedFinalCode(), secondChild.getResolvedFinalPath());
        Assertions.assertEquals(root.getResolvedFinalPath() + "/" + thirdChild.getResolvedFinalCode(), thirdChild.getResolvedFinalPath());
    }

    @Test
    void dryRun_shouldKeepDistinctAutoCodesForRootCategories() throws Exception {
        String suffix = uniqueSuffix();
        String firstRootCode = "ROOT-A-" + suffix;
        String secondRootCode = "ROOT-B-" + suffix;
        MockMultipartFile workbook = createWorkbook(
                "workbook-auto-category-roots-" + suffix + ".xlsx",
                List.<String[]>of(
                        new String[]{"MATERIAL", firstRootCode, "/" + firstRootCode, "Root A " + suffix},
                        new String[]{"MATERIAL", secondRootCode, "/" + secondRootCode, "Root B " + suffix}
                ),
                List.of(),
                List.of());

        WorkbookImportDryRunResponseDto response = dryRunService.dryRun(workbook, "it-user", autoOptions());

        Assertions.assertEquals(2, response.getPreview().getCategories().size());

        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto firstRoot = response.getPreview().getCategories().get(0);
        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto secondRoot = response.getPreview().getCategories().get(1);

        Assertions.assertEquals("SYSTEM_RULE_AUTO", firstRoot.getCodeMode());
        Assertions.assertEquals("SYSTEM_RULE_AUTO", secondRoot.getCodeMode());
        Assertions.assertNotEquals(firstRoot.getResolvedFinalCode(), secondRoot.getResolvedFinalCode());
        Assertions.assertEquals("/" + firstRoot.getResolvedFinalCode(), firstRoot.getResolvedFinalPath());
        Assertions.assertEquals("/" + secondRoot.getResolvedFinalCode(), secondRoot.getResolvedFinalPath());
    }

    @Test
    void dryRun_shouldErrorWhenAutoCategoryCodePreviewFallsBack() throws Exception {
        String prefix = "WB" + uniqueSuffix().substring(0, 4);
        MetaCodeRule categoryRule = codeRuleRepository.findByCode("CATEGORY").orElseThrow();
        categoryRule.setStatus("DRAFT");
        categoryRule.setActive(Boolean.FALSE);
        codeRuleRepository.save(categoryRule);

        CodeRuleSaveRequestDto request = new CodeRuleSaveRequestDto();
        request.setBusinessDomain("MATERIAL");
        request.setRuleCode("CATEGORY");
        request.setName("Category");
        request.setTargetType("CATEGORY");
        request.setScopeType("BUSINESS_DOMAIN");
        request.setPattern(prefix);
        request.setAllowManualOverride(Boolean.TRUE);
        request.setRegexPattern("^[A-Z][A-Z0-9_-]{0,127}$");
        request.setMaxLength(128);
        request.setRuleJson(buildStructuredCategoryRuleJsonWithoutSequence(prefix));

        codeRuleService.update("CATEGORY", request, "it-user");
        codeRuleService.publish("CATEGORY", "it-user");

        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createWorkbook(
                "workbook-auto-category-preview-fail-" + suffix + ".xlsx",
            List.<String[]>of(
                new String[]{"MATERIAL", "CAT-A-" + suffix, "/CAT-A-" + suffix, "Category A " + suffix},
                new String[]{"MATERIAL", "CAT-B-" + suffix, "/CAT-B-" + suffix, "Category B " + suffix}
            ),
                List.of(),
                List.of());

        WorkbookImportDryRunResponseDto response = dryRunService.dryRun(workbook, "it-user", autoOptions());

        Assertions.assertFalse(Boolean.TRUE.equals(response.getSummary().getCanImport()));
        Assertions.assertTrue(response.getSummary().getErrorCount() >= 1);
        Assertions.assertEquals(2, response.getPreview().getCategories().size());
        Assertions.assertTrue(response.getPreview().getCategories().stream().allMatch(item -> item.getResolvedFinalCode() == null));
        WorkbookImportDryRunResponseDto.IssueDto issue = response.getIssues().stream()
                .filter(item -> "CATEGORY_AUTO_CODE_PREVIEW_FAILED".equals(item.getErrorCode()))
                .findFirst()
                .orElseThrow();
        Assertions.assertEquals("Category_Code", issue.getColumnName());
    }

        @Test
        void dryRun_shouldReportInvalidDataTypeWithSupportedValues() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createWorkbook(
            "workbook-invalid-type-" + suffix + ".xlsx",
            List.<String[]>of(new String[]{"MATERIAL", "TYPE-" + suffix, "/TYPE-" + suffix, "Type Category " + suffix}),
            List.<String[]>of(attributeRow("TYPE-" + suffix, "Type Category " + suffix, "ATTR-TYPE-" + suffix, "Broken Attr " + suffix, "broken" + suffix.toLowerCase(), "enum_bad")),
            List.of());

        WorkbookImportDryRunResponseDto response = dryRunService.dryRun(workbook, "it-user", manualKeepExistingOptions());

        Assertions.assertFalse(Boolean.TRUE.equals(response.getSummary().getCanImport()));
        Assertions.assertTrue(response.getSummary().getErrorCount() >= 1);
        WorkbookImportDryRunResponseDto.IssueDto issue = response.getIssues().stream()
            .filter(item -> "ATTRIBUTE_DATA_TYPE_INVALID".equals(item.getErrorCode()))
            .findFirst()
            .orElseThrow();
        Assertions.assertEquals("Data_Type", issue.getColumnName());
        Assertions.assertEquals("enum_bad", issue.getRawValue());
        Assertions.assertTrue(issue.getExpectedRule().contains("string"));
        Assertions.assertTrue(issue.getExpectedRule().contains("multi_enum"));
        }

    @Test
    void startImport_shouldPersistEntitiesAndExposeCompletedJobStatusAndLogs() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createAutoWorkbook(suffix);
        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", autoOptions());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setImportSessionId(dryRun.getImportSessionId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.TRUE);

        WorkbookImportStartResponseDto start = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(start.getJobId());
        WorkbookImportLogPageDto logs = runtimeService.getLogs(start.getJobId(), null, 200, null, null, null, null);

        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals(5, status.getTotalRows());
        Assertions.assertEquals(5, status.getProcessedRows());
        Assertions.assertEquals(WorkbookImportSupport.STAGE_FINALIZING, status.getCurrentStage());
        Assertions.assertEquals(100, status.getOverallPercent());
        Assertions.assertEquals(2, status.getProgress().getCategories().getCreated());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getCreated());
        Assertions.assertEquals(2, status.getProgress().getEnumOptions().getCreated());
        Assertions.assertEquals(2, status.getProgress().getCategories().getProcessed());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getProcessed());
        Assertions.assertEquals(2, status.getProgress().getEnumOptions().getProcessed());

        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_CODE_SEQUENCE_RESERVED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_CODE_SEQUENCE_RESERVED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_CODE_SEQUENCE_RESERVED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_BATCH_UPSERTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_BATCH_UPSERTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_IMPORTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_IMPORTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_IMPORTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_CLOSURE_INCREMENTAL_REUSED"));

        List<WorkbookImportLogEventDto> categoryImportedLogs = logs.getItems().stream()
            .filter(item -> "CATEGORY_IMPORTED".equals(item.getCode()))
            .toList();
        WorkbookImportLogEventDto attributeImportedLog = logs.getItems().stream()
            .filter(item -> "ATTRIBUTE_IMPORTED".equals(item.getCode()))
            .findFirst()
            .orElseThrow();
        List<WorkbookImportLogEventDto> enumImportedLogs = logs.getItems().stream()
            .filter(item -> "ENUM_OPTION_IMPORTED".equals(item.getCode()))
            .toList();

        Assertions.assertEquals(2, categoryImportedLogs.size());
        Assertions.assertEquals(2, enumImportedLogs.size());

        for (WorkbookImportLogEventDto categoryLog : categoryImportedLogs) {
            Assertions.assertTrue(categoryDefRepository.findByBusinessDomainAndCodeKey("MATERIAL", categoryLog.getEntityKey()).isPresent());
        }

        String[] attributeKeyParts = attributeImportedLog.getEntityKey().split("/");
        String actualAttributeKey = attributeKeyParts[attributeKeyParts.length - 1];
        MetaAttributeDefDetailDto detail = attributeQueryService.detail("MATERIAL", actualAttributeKey, true);
        Assertions.assertNotNull(detail);
        Assertions.assertEquals("Color " + suffix, detail.getLatestVersion().getDisplayName());
        Assertions.assertEquals(2, detail.getLovValues().size());

        List<String> actualEnumCodes = enumImportedLogs.stream()
            .map(WorkbookImportLogEventDto::getEntityKey)
            .map(entityKey -> entityKey.substring(entityKey.lastIndexOf('/') + 1))
            .toList();
        Assertions.assertEquals(actualEnumCodes.get(0), detail.getLovValues().get(0).getCode());
        Assertions.assertEquals(actualEnumCodes.get(1), detail.getLovValues().get(1).getCode());

        WorkbookImportDryRunResponseDto.AttributePreviewItemDto attributePreview = dryRun.getPreview().getAttributes().get(0);
        Assertions.assertTrue(actualAttributeKey.startsWith("ATTR-"), "actual attribute key=" + actualAttributeKey);
        Assertions.assertTrue(attributePreview.getResolvedFinalCode().startsWith("ATTR-"), "preview attribute key=" + attributePreview.getResolvedFinalCode());
    }

    @Test
    void dryRun_shouldPreviewMoreThanTwentyAutoAttributeCodesInSameCategory() throws Exception {
        String suffix = uniqueSuffix();
        String categoryCode = "AUTO-CAT-" + suffix;
        List<String[]> attributeRows = new java.util.ArrayList<>();
        for (int index = 1; index <= 25; index++) {
            String attributeKey = "ATTR-REF-" + suffix + "-" + String.format("%02d", index);
            attributeRows.add(attributeRow(
                    categoryCode,
                    "Auto Category " + suffix,
                    attributeKey,
                    "Auto Attr " + index,
                    "autoField" + index,
                    "string"));
        }

        MockMultipartFile workbook = createWorkbook(
                "workbook-auto-attribute-bulk-" + suffix + ".xlsx",
                List.<String[]>of(new String[]{"MATERIAL", categoryCode, "/" + categoryCode, "Auto Category " + suffix}),
                attributeRows,
                List.of());

        WorkbookImportDryRunResponseDto response = dryRunService.dryRun(workbook, "it-user", manualCategoryAutoAttributeOptions());

        Assertions.assertEquals(25, response.getPreview().getAttributes().size());
        Assertions.assertTrue(response.getPreview().getAttributes().stream().allMatch(item -> "SYSTEM_RULE_AUTO".equals(item.getCodeMode())));
        Assertions.assertTrue(response.getPreview().getAttributes().stream().allMatch(item -> item.getResolvedFinalCode() != null && !item.getResolvedFinalCode().equals(item.getAttributeKey())));
        Assertions.assertNotEquals(
                response.getPreview().getAttributes().get(24).getAttributeKey(),
                response.getPreview().getAttributes().get(24).getResolvedFinalCode());
    }

    @Test
    void startImport_shouldSupportStageTransactionModeAndClosureCompensation() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createAutoWorkbook(suffix);
        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", autoOptions());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setImportSessionId(dryRun.getImportSessionId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.FALSE);
        request.setExecutionMode("STAGE_TX");

        WorkbookImportStartResponseDto start = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(start.getJobId());
        WorkbookImportPostProcessResponseDto postProcess = executionService.rebuildCategoryClosure(start.getJobId(), "repair-user");
        WorkbookImportLogPageDto logs = runtimeService.getLogs(start.getJobId(), null, 200, null, null, null, null);

        Assertions.assertEquals(Boolean.FALSE, start.getAtomic());
        Assertions.assertEquals("STAGE_TX", start.getExecutionMode());
        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals("STAGE_TX", status.getExecutionMode());
        Assertions.assertEquals("REBUILD_CLOSURE", postProcess.getAction());
        Assertions.assertEquals("COMPLETED", postProcess.getStatus());
        Assertions.assertEquals("STAGE_TX", postProcess.getExecutionMode());
        Assertions.assertNotNull(postProcess.getDetails());
        Assertions.assertEquals("ancestor_list_dp", postProcess.getDetails().get("strategy"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_CLOSURE_REBUILD_COMPENSATED"));
    }

    @Test
    void startImport_shouldPrepareAndClearStagedPlanAfterStagingAtomicSuccess() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createAutoWorkbook(suffix);
        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", autoOptions());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setImportSessionId(dryRun.getImportSessionId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.TRUE);
        request.setExecutionMode("STAGING_ATOMIC");

        WorkbookImportStartResponseDto start = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(start.getJobId());
        WorkbookImportLogPageDto logs = runtimeService.getLogs(start.getJobId(), null, 200, null, null, null, null);

        runtimeService.evictSessionCache(dryRun.getImportSessionId());
        WorkbookImportSupport.ImportSessionState restored = runtimeService.getSession(dryRun.getImportSessionId());

        Assertions.assertEquals(Boolean.TRUE, start.getAtomic());
        Assertions.assertEquals("STAGING_ATOMIC", start.getExecutionMode());
        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals("STAGING_ATOMIC", status.getExecutionMode());
        Assertions.assertNull(restored.stagedExecutionPlan());
        Assertions.assertTrue(hasLogCode(logs.getItems(), "WORKBOOK_STAGING_PLAN_PREPARED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "WORKBOOK_STAGING_MERGE_STARTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "WORKBOOK_STAGING_PLAN_CLEARED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_BATCH_UPSERTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_BATCH_UPSERTED"));
    }

    @Test
    void startImport_shouldRetainFailedStagedPlanReuseOnRetryAndBlockConcurrentSessionImport() throws Exception {
        String suffix = uniqueSuffix();
        String categoryCode = "STAGE-CAT-" + suffix;
        String attributeKey = "ATTR_STAGE_" + suffix;
        String enumCode = "ENUM_STAGE_" + suffix;
        MockMultipartFile workbook = createWorkbook(
            "workbook-staging-retry-" + suffix + ".xlsx",
            List.<String[]>of(new String[]{"MATERIAL", categoryCode, "/" + categoryCode, "Stage Category " + suffix}),
            List.<String[]>of(attributeRow(categoryCode, "Stage Category " + suffix, attributeKey, "Stage Attribute " + suffix, "stage" + suffix.toLowerCase(), "enum")),
            List.<String[]>of(new String[]{categoryCode, attributeKey, enumCode, "Stage Enabled " + suffix, "Stage Enabled " + suffix})
        );
        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", manualKeepExistingOptions());
        WorkbookImportSupport.ImportSessionState session = runtimeService.getSession(dryRun.getImportSessionId());

        WorkbookImportSupport.CategoryPlanItem originalFirstCategory = session.executionPlan().categories().get(0);
        WorkbookImportSupport.CategoryPlanItem conflictingFirstCategory = new WorkbookImportSupport.CategoryPlanItem(
                originalFirstCategory.sheetName(),
                originalFirstCategory.rowNumber(),
                originalFirstCategory.businessDomain(),
                originalFirstCategory.excelReferenceCode(),
                originalFirstCategory.categoryPath(),
                originalFirstCategory.categoryName(),
                originalFirstCategory.parentPath(),
                originalFirstCategory.resolvedFinalCode(),
                originalFirstCategory.resolvedFinalPath(),
                "CONFLICT",
                "CATEGORY_CONFLICT",
                originalFirstCategory.existingCategoryId(),
                originalFirstCategory.oldStateHash(),
                originalFirstCategory.newStateHash(),
                false,
                originalFirstCategory.codeMode());
        WorkbookImportSupport.ExecutionPlanSnapshot invalidStagedPlan = new WorkbookImportSupport.ExecutionPlanSnapshot(
                java.util.stream.Stream.concat(
                        java.util.stream.Stream.of(conflictingFirstCategory),
                        session.executionPlan().categories().stream().skip(1))
                        .toList(),
                session.executionPlan().attributes(),
                session.executionPlan().enumOptions());
        runtimeService.saveStagedExecutionPlan(dryRun.getImportSessionId(), invalidStagedPlan);

        WorkbookImportStartRequestDto firstRequest = new WorkbookImportStartRequestDto();
        firstRequest.setImportSessionId(dryRun.getImportSessionId());
        firstRequest.setOperator("it-user");
        firstRequest.setAtomic(Boolean.TRUE);
        firstRequest.setExecutionMode("STAGING_ATOMIC");

        WorkbookImportStartResponseDto failedStart = executionService.startImport(firstRequest);
        WorkbookImportJobStatusDto failedStatus = runtimeService.getJobStatus(failedStart.getJobId());
        WorkbookImportLogPageDto failedLogs = runtimeService.getLogs(failedStart.getJobId(), null, 200, null, null, null, null);

        runtimeService.evictSessionCache(dryRun.getImportSessionId());
        WorkbookImportSupport.ImportSessionState retainedSession = runtimeService.getSession(dryRun.getImportSessionId());

        Assertions.assertEquals(WorkbookImportSupport.STATUS_FAILED, failedStatus.getStatus());
        Assertions.assertNotNull(retainedSession.stagedExecutionPlan());
        Assertions.assertTrue(hasLogCode(failedLogs.getItems(), "WORKBOOK_STAGING_PLAN_REUSED"));
        Assertions.assertTrue(hasLogCode(failedLogs.getItems(), "WORKBOOK_STAGING_PLAN_RETAINED"));

        runtimeService.saveStagedExecutionPlan(dryRun.getImportSessionId(), session.executionPlan());

        WorkbookImportStartRequestDto retryRequest = new WorkbookImportStartRequestDto();
        retryRequest.setImportSessionId(dryRun.getImportSessionId());
        retryRequest.setOperator("it-user");
        retryRequest.setAtomic(Boolean.TRUE);
        retryRequest.setExecutionMode("STAGING_ATOMIC");

        WorkbookImportStartResponseDto retryStart = executionService.startImport(retryRequest);
        WorkbookImportJobStatusDto retryStatus = runtimeService.getJobStatus(retryStart.getJobId());
        WorkbookImportLogPageDto retryLogs = runtimeService.getLogs(retryStart.getJobId(), null, 200, null, null, null, null);

        runtimeService.evictSessionCache(dryRun.getImportSessionId());
        WorkbookImportSupport.ImportSessionState clearedSession = runtimeService.getSession(dryRun.getImportSessionId());

        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, retryStatus.getStatus());
        Assertions.assertTrue(hasLogCode(retryLogs.getItems(), "WORKBOOK_STAGING_PLAN_REUSED"));
        Assertions.assertTrue(hasLogCode(retryLogs.getItems(), "WORKBOOK_STAGING_PLAN_CLEARED"));
        Assertions.assertNull(clearedSession.stagedExecutionPlan());

        WorkbookImportSupport.JobState activeJob = runtimeService.createJob(session, "it-user", true, "STAGING_ATOMIC");
        try {
            IllegalStateException exception = Assertions.assertThrows(IllegalStateException.class, () ->
                    executionService.startImport(retryRequest));
            Assertions.assertTrue(exception.getMessage().contains("already running"));
        } finally {
            runtimeService.failJob(activeJob.getJobId(), "cleanup");
        }
    }

    @Test
    void startImport_shouldSkipExistingRowsWhenDuplicatePolicyIsKeepExisting() throws Exception {
        String suffix = uniqueSuffix();
        String categoryCode = "KEEP-CAT-" + suffix;
        String attributeKey = "ATTR_KEEP_" + suffix;
        String enumCode = "ENUM_KEEP_" + suffix;

        createCategory(categoryCode, "Existing Category " + suffix);
        createManualEnumAttribute(categoryCode, attributeKey, enumCode, "Existing Status " + suffix, "Enabled " + suffix);

        MockMultipartFile workbook = createKeepExistingWorkbook(categoryCode, attributeKey, enumCode, suffix);
        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", manualKeepExistingOptions());

        Assertions.assertTrue(Boolean.TRUE.equals(dryRun.getSummary().getCanImport()));
        Assertions.assertEquals("KEEP_EXISTING", dryRun.getPreview().getCategories().get(0).getResolvedAction());
        Assertions.assertEquals("KEEP_EXISTING", dryRun.getPreview().getAttributes().get(0).getResolvedAction());
        Assertions.assertEquals("KEEP_EXISTING", dryRun.getPreview().getEnumOptions().get(0).getResolvedAction());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setImportSessionId(dryRun.getImportSessionId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.TRUE);

        WorkbookImportStartResponseDto start = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(start.getJobId());
        WorkbookImportLogPageDto logs = runtimeService.getLogs(start.getJobId(), null, 100, null, null, null, null);

        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals(1, status.getProgress().getCategories().getSkipped());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getSkipped());
        Assertions.assertEquals(1, status.getProgress().getEnumOptions().getSkipped());
        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_SKIPPED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_SKIPPED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_SKIPPED"));

        MetaAttributeDefDetailDto detail = attributeQueryService.detail("MATERIAL", attributeKey, true);
        Assertions.assertEquals("Existing Status " + suffix, detail.getLatestVersion().getDisplayName());
        Assertions.assertEquals(1, detail.getLovValues().size());
        Assertions.assertEquals(enumCode, detail.getLovValues().get(0).getCode());
        Assertions.assertEquals("Enabled " + suffix, detail.getLovValues().get(0).getValue());
    }

        @Test
        void startImport_shouldSkipNoChangeRowsWhenDuplicatePolicyIsOverwrite() throws Exception {
        String suffix = uniqueSuffix();
        String categoryCode = "OVERWRITE-CAT-" + suffix;
        String categoryName = "Overwrite Category " + suffix;
        String attributeKey = "ATTR_OVERWRITE_" + suffix;
        String attributeName = "Overwrite Status " + suffix;
        String attributeField = "status" + suffix.toLowerCase();
        String enumCode = "ENUM_OVERWRITE_" + suffix;
        String optionName = "Enabled " + suffix;

        createCategory(categoryCode, categoryName);
        createManualEnumAttribute(categoryCode, attributeKey, enumCode, attributeName, attributeField, optionName, optionName);

        MetaAttributeDefDetailDto beforeDetail = attributeQueryService.detail("MATERIAL", attributeKey, true);
        Integer beforeAttributeVersion = beforeDetail.getLatestVersion().getVersionNo();
        Integer beforeLovVersion = lovVersionRepository.findLatestByDef(
            lovDefRepository.findByBusinessDomainAndKey("MATERIAL", beforeDetail.getLovKey()).orElseThrow())
            .orElseThrow()
            .getVersionNo();

        MockMultipartFile workbook = createWorkbook(
            "workbook-overwrite-no-change-" + suffix + ".xlsx",
            List.<String[]>of(new String[]{"MATERIAL", categoryCode, "/" + categoryCode, categoryName}),
            List.<String[]>of(attributeRow(categoryCode, categoryName, attributeKey, attributeName, attributeField, "enum")),
            List.<String[]>of(new String[]{categoryCode, attributeKey, enumCode, optionName, optionName})
        );

        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", manualOverwriteOptions());

        Assertions.assertTrue(Boolean.TRUE.equals(dryRun.getSummary().getCanImport()));
        Assertions.assertEquals("SKIP_NO_CHANGE", dryRun.getPreview().getCategories().get(0).getResolvedAction());
        Assertions.assertEquals("SKIP_NO_CHANGE", dryRun.getPreview().getAttributes().get(0).getResolvedAction());
        Assertions.assertEquals("SKIP_NO_CHANGE", dryRun.getPreview().getEnumOptions().get(0).getResolvedAction());
        Assertions.assertEquals(1, dryRun.getChangeSummary().getCategories().getSkip());
        Assertions.assertEquals(1, dryRun.getChangeSummary().getAttributes().getSkip());
        Assertions.assertEquals(1, dryRun.getChangeSummary().getEnumOptions().getSkip());
        WorkbookImportSupport.ImportSessionState session = runtimeService.getSession(dryRun.getImportSessionId());
        Assertions.assertFalse(session.executionPlan().categories().get(0).shouldWrite());
        Assertions.assertNotNull(session.executionPlan().categories().get(0).existingCategoryId());
        Assertions.assertEquals(session.executionPlan().categories().get(0).oldStateHash(), session.executionPlan().categories().get(0).newStateHash());
        Assertions.assertFalse(session.executionPlan().attributes().get(0).shouldWrite());
        Assertions.assertNotNull(session.executionPlan().attributes().get(0).existingAttributeId());
        Assertions.assertEquals(session.executionPlan().attributes().get(0).oldStructureHash(), session.executionPlan().attributes().get(0).newStructureHash());
        Assertions.assertFalse(session.executionPlan().enumOptions().get(0).shouldWrite());
        Assertions.assertEquals(enumCode, session.executionPlan().enumOptions().get(0).existingOptionCode());
        Assertions.assertEquals(session.executionPlan().enumOptions().get(0).oldValueHash(), session.executionPlan().enumOptions().get(0).newValueHash());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setImportSessionId(dryRun.getImportSessionId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.TRUE);

        WorkbookImportStartResponseDto start = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(start.getJobId());
        WorkbookImportLogPageDto logs = runtimeService.getLogs(start.getJobId(), null, 100, null, null, null, null);

        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals(1, status.getProgress().getCategories().getSkipped());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getSkipped());
        Assertions.assertEquals(1, status.getProgress().getEnumOptions().getSkipped());
        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_SKIPPED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_SKIPPED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_SKIPPED"));

        MetaAttributeDefDetailDto afterDetail = attributeQueryService.detail("MATERIAL", attributeKey, true);
        Integer afterAttributeVersion = afterDetail.getLatestVersion().getVersionNo();
        Integer afterLovVersion = lovVersionRepository.findLatestByDef(
            lovDefRepository.findByBusinessDomainAndKey("MATERIAL", afterDetail.getLovKey()).orElseThrow())
            .orElseThrow()
            .getVersionNo();
        Assertions.assertEquals(beforeAttributeVersion, afterAttributeVersion);
        Assertions.assertEquals(beforeLovVersion, afterLovVersion);
        Assertions.assertEquals(optionName, afterDetail.getLovValues().get(0).getValue());
        }

    @Test
    void startImport_shouldReusePreloadedExistingDataWhenWorkbookOmitsCategorySheetRows() throws Exception {
        String suffix = uniqueSuffix();
        String categoryCode = "DB-CAT-" + suffix;
        String attributeKey = "ATTR_DB_" + suffix;
        String enumCode = "ENUM_DB_" + suffix;

        createCategory(categoryCode, "Database Category " + suffix);
        createManualEnumAttribute(categoryCode, attributeKey, enumCode, "Database Status " + suffix, "Database Enabled " + suffix);

        MockMultipartFile workbook = createWorkbook(
                "workbook-db-ref-" + suffix + ".xlsx",
            List.<String[]>of(),
            List.<String[]>of(attributeRow(categoryCode, "Database Category " + suffix, attributeKey, "Workbook Status " + suffix, "status" + suffix.toLowerCase(), "enum")),
            List.<String[]>of(new String[]{categoryCode, attributeKey, enumCode, "Workbook Enabled " + suffix, "Workbook Enabled " + suffix})
        );

        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", manualKeepExistingOptions());

        Assertions.assertTrue(Boolean.TRUE.equals(dryRun.getSummary().getCanImport()));
        Assertions.assertEquals(0, dryRun.getSummary().getCategoryRowCount());
        Assertions.assertEquals("KEEP_EXISTING", dryRun.getPreview().getAttributes().get(0).getResolvedAction());
        Assertions.assertEquals("KEEP_EXISTING", dryRun.getPreview().getEnumOptions().get(0).getResolvedAction());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setImportSessionId(dryRun.getImportSessionId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.TRUE);

        WorkbookImportStartResponseDto start = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(start.getJobId());
        WorkbookImportLogPageDto logs = runtimeService.getLogs(start.getJobId(), null, 100, null, null, null, null);

        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals(0, status.getProgress().getCategories().getTotal());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getSkipped());
        Assertions.assertEquals(1, status.getProgress().getEnumOptions().getSkipped());
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_SKIPPED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_SKIPPED"));
    }

    @Test
    void getSession_shouldRestoreSnapshotAfterCacheEviction() throws Exception {
        String suffix = uniqueSuffix();
        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(createAutoWorkbook(suffix), "it-user", autoOptions());

        runtimeService.evictSessionCache(dryRun.getImportSessionId());
        WorkbookImportSupport.ImportSessionState restored = runtimeService.getSession(dryRun.getImportSessionId());

        Assertions.assertEquals(dryRun.getImportSessionId(), restored.importSessionId());
        Assertions.assertNotNull(restored.executionPlan());
        Assertions.assertEquals(2, restored.executionPlan().categories().size());
        Assertions.assertEquals(1, restored.executionPlan().attributes().size());
        Assertions.assertEquals(2, restored.executionPlan().enumOptions().size());
        Assertions.assertTrue(restored.executionPlan().categories().get(0).shouldWrite());
        Assertions.assertNotNull(restored.executionPlan().attributes().get(0).newStructureHash());
        Assertions.assertNotNull(restored.executionPlan().enumOptions().get(0).newValueHash());
    }

    @Test
    void startImport_shouldAcceptDryRunJobIdAndRestoreSnapshotFromPersistence() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createAutoWorkbook(suffix);

        WorkbookImportDryRunStartResponseDto startDryRun = dryRunJobService.startDryRun(workbook, "it-user", autoOptions());
        WorkbookImportDryRunResponseDto dryRun = runtimeService.getDryRunResult(startDryRun.getJobId());
        runtimeService.evictSessionCache(dryRun.getImportSessionId());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setDryRunJobId(startDryRun.getJobId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.TRUE);

        WorkbookImportStartResponseDto startImport = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(startImport.getJobId());

        Assertions.assertEquals(dryRun.getImportSessionId(), startImport.getImportSessionId());
        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals(2, status.getProgress().getCategories().getCreated());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getCreated());
        Assertions.assertEquals(2, status.getProgress().getEnumOptions().getCreated());
    }

    private WorkbookImportDryRunOptionsDto autoOptions() {
        WorkbookImportDryRunOptionsDto options = new WorkbookImportDryRunOptionsDto();
        options.getCodingOptions().setCategoryCodeMode("SYSTEM_RULE_AUTO");
        options.getCodingOptions().setAttributeCodeMode("SYSTEM_RULE_AUTO");
        options.getCodingOptions().setEnumOptionCodeMode("SYSTEM_RULE_AUTO");
        options.getDuplicateOptions().setCategoryDuplicatePolicy("FAIL_ON_DUPLICATE");
        options.getDuplicateOptions().setAttributeDuplicatePolicy("FAIL_ON_DUPLICATE");
        options.getDuplicateOptions().setEnumOptionDuplicatePolicy("FAIL_ON_DUPLICATE");
        return options;
    }

    private WorkbookImportDryRunOptionsDto manualKeepExistingOptions() {
        WorkbookImportDryRunOptionsDto options = new WorkbookImportDryRunOptionsDto();
        options.getCodingOptions().setCategoryCodeMode("EXCEL_MANUAL");
        options.getCodingOptions().setAttributeCodeMode("EXCEL_MANUAL");
        options.getCodingOptions().setEnumOptionCodeMode("EXCEL_MANUAL");
        options.getDuplicateOptions().setCategoryDuplicatePolicy("KEEP_EXISTING");
        options.getDuplicateOptions().setAttributeDuplicatePolicy("KEEP_EXISTING");
        options.getDuplicateOptions().setEnumOptionDuplicatePolicy("KEEP_EXISTING");
        return options;
    }

    private WorkbookImportDryRunOptionsDto manualOverwriteOptions() {
        WorkbookImportDryRunOptionsDto options = new WorkbookImportDryRunOptionsDto();
        options.getCodingOptions().setCategoryCodeMode("EXCEL_MANUAL");
        options.getCodingOptions().setAttributeCodeMode("EXCEL_MANUAL");
        options.getCodingOptions().setEnumOptionCodeMode("EXCEL_MANUAL");
        options.getDuplicateOptions().setCategoryDuplicatePolicy("OVERWRITE_EXISTING");
        options.getDuplicateOptions().setAttributeDuplicatePolicy("OVERWRITE_EXISTING");
        options.getDuplicateOptions().setEnumOptionDuplicatePolicy("OVERWRITE_EXISTING");
        return options;
    }

    private WorkbookImportDryRunOptionsDto manualCategoryAutoAttributeOptions() {
        WorkbookImportDryRunOptionsDto options = new WorkbookImportDryRunOptionsDto();
        options.getCodingOptions().setCategoryCodeMode("EXCEL_MANUAL");
        options.getCodingOptions().setAttributeCodeMode("SYSTEM_RULE_AUTO");
        options.getCodingOptions().setEnumOptionCodeMode("EXCEL_MANUAL");
        options.getDuplicateOptions().setCategoryDuplicatePolicy("FAIL_ON_DUPLICATE");
        options.getDuplicateOptions().setAttributeDuplicatePolicy("FAIL_ON_DUPLICATE");
        options.getDuplicateOptions().setEnumOptionDuplicatePolicy("FAIL_ON_DUPLICATE");
        return options;
    }

    private java.util.Map<String, Object> buildStructuredCategoryRuleJsonWithoutSequence(String prefix) {
        java.util.LinkedHashMap<String, Object> subRule = new java.util.LinkedHashMap<>();
        subRule.put("separator", "-");
        subRule.put("segments", List.of(java.util.Map.of("type", "STRING", "value", prefix)));
        subRule.put("childSegments", List.of(java.util.Map.of("type", "STRING", "value", "CHILD")));
        subRule.put("allowedVariableKeys", List.of("BUSINESS_DOMAIN", "PARENT_CODE"));

        java.util.LinkedHashMap<String, Object> root = new java.util.LinkedHashMap<>();
        root.put("pattern", "STRUCTURED");
        root.put("hierarchyMode", "APPEND_CHILD_SUFFIX");
        root.put("subRules", java.util.Map.of("category", subRule));
        root.put("validation", java.util.Map.of(
                "maxLength", 128,
                "regex", "^[A-Z][A-Z0-9_-]{0,127}$",
                "allowManualOverride", true
        ));
        return root;
    }

    private void createCategory(String code, String name) {
        CreateCategoryRequestDto request = new CreateCategoryRequestDto();
        request.setBusinessDomain("MATERIAL");
        request.setCode(code);
        request.setName(name);
        categoryCrudService.create(request, "it-user");
    }

    private void createManualEnumAttribute(String categoryCode,
                                           String attributeKey,
                                           String enumCode,
                                           String attributeName,
                                           String optionName) {
        createManualEnumAttribute(categoryCode, attributeKey, enumCode, attributeName, "status" + uniqueSuffix().toLowerCase(), optionName, optionName);
    }

    private void createManualEnumAttribute(String categoryCode,
                                           String attributeKey,
                                           String enumCode,
                                           String attributeName,
                                           String attributeField,
                                           String optionName,
                                           String optionLabel) {
        MetaAttributeUpsertRequestDto request = new MetaAttributeUpsertRequestDto();
        request.setKey(attributeKey);
        request.setGenerationMode("MANUAL");
        request.setDisplayName(attributeName);
        request.setAttributeField(attributeField);
        request.setDataType("enum");
        request.setRequired(Boolean.FALSE);
        request.setUnique(Boolean.FALSE);
        request.setSearchable(Boolean.TRUE);
        request.setHidden(Boolean.FALSE);
        request.setReadOnly(Boolean.FALSE);
        request.setLovKey(attributeKey + "_LOV");
        request.setLovGenerationMode("MANUAL");
        request.setLovValues(List.of(lovValue(enumCode, optionName, optionLabel)));
        attributeManageService.create(categoryCode, request, "it-user");
    }

    private MetaAttributeUpsertRequestDto.LovValueUpsertItem lovValue(String code, String name) {
        return lovValue(code, name, name);
    }

    private MetaAttributeUpsertRequestDto.LovValueUpsertItem lovValue(String code, String name, String label) {
        MetaAttributeUpsertRequestDto.LovValueUpsertItem item = new MetaAttributeUpsertRequestDto.LovValueUpsertItem();
        item.setCode(code);
        item.setName(name);
        item.setLabel(label);
        return item;
    }

    private boolean hasLogCode(List<WorkbookImportLogEventDto> items, String code) {
        return items.stream().map(WorkbookImportLogEventDto::getCode).anyMatch(code::equals);
    }

    private MockMultipartFile createAutoWorkbook(String suffix) throws Exception {
        String rootCode = "ROOT-" + suffix;
        String childCode = "CHILD-" + suffix;
        String attributeCode = "ATTR-REF-" + suffix;
        return createWorkbook(
                "workbook-auto-" + suffix + ".xlsx",
            List.<String[]>of(
                        new String[]{"MATERIAL", rootCode, "/" + rootCode, "Root " + suffix},
                        new String[]{"MATERIAL", childCode, "/" + rootCode + "/" + childCode, "Child " + suffix}
                ),
            List.<String[]>of(
                        attributeRow(childCode, "Child " + suffix, attributeCode, "Color " + suffix, "color" + suffix.toLowerCase(), "enum")
                ),
            List.<String[]>of(
                        new String[]{childCode, attributeCode, "ENUM-REF-A-" + suffix, "Red " + suffix, "Red " + suffix},
                        new String[]{childCode, attributeCode, "ENUM-REF-B-" + suffix, "Blue " + suffix, "Blue " + suffix}
                )
        );
    }

    private MockMultipartFile createKeepExistingWorkbook(String categoryCode,
                                                         String attributeKey,
                                                         String enumCode,
                                                         String suffix) throws Exception {
        return createWorkbook(
                "workbook-keep-" + suffix + ".xlsx",
            List.<String[]>of(new String[]{"MATERIAL", categoryCode, "/" + categoryCode, "Workbook Category " + suffix}),
            List.<String[]>of(attributeRow(categoryCode, "Workbook Category " + suffix, attributeKey, "Workbook Status " + suffix, "status" + suffix.toLowerCase(), "enum")),
            List.<String[]>of(new String[]{categoryCode, attributeKey, enumCode, "Workbook Enabled " + suffix, "Workbook Enabled " + suffix})
        );
    }

    private String[] attributeRow(String categoryCode,
                                  String categoryName,
                                  String attributeKey,
                                  String attributeName,
                                  String attributeField,
                                  String dataType) {
        return new String[]{
                categoryCode,
                categoryName,
                attributeKey,
                attributeName,
                attributeField,
                "",
                dataType,
                "",
                "",
                "N",
                "N",
                "Y",
                "N",
                "N",
                "",
                "",
                "",
                "",
                "",
                ""
        };
    }

    private MockMultipartFile createWorkbook(String fileName,
                                             List<String[]> categoryRows,
                                             List<String[]> attributeRows,
                                             List<String[]> enumRows) throws Exception {
        try (XSSFWorkbook workbook = new XSSFWorkbook(); ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            Sheet categories = workbook.createSheet("分类层级");
            writeRow(categories, 0, "分类层级：填写真实编码、完整路径、分类名称，右侧自动校验与预览");
            writeRow(categories, 1, "", "用户填写区", "", "");
            writeRow(categories, 2, "Business_Domain", "Category_Code", "Category_Path", "Category_Name");
            for (int index = 0; index < categoryRows.size(); index++) {
                writeRow(categories, index + 3, categoryRows.get(index));
            }

            Sheet attributes = workbook.createSheet("属性定义");
            writeRow(attributes, 0, "属性定义：填写属性基础信息，前两行为模板说明与表头");
            writeRow(attributes, 1,
                    "Category_Code",
                    "Category_Name",
                    "Attribute_Key",
                    "Attribute_Name",
                    "Attribute_Field",
                    "Description",
                    "Data_Type",
                    "Unit",
                    "Default_Value",
                    "Required",
                    "Unique",
                    "Searchable",
                    "Hidden",
                    "Read_Only",
                    "Min_Value",
                    "Max_Value",
                    "Step",
                    "Precision",
                    "True_Label",
                    "False_Label");
            for (int index = 0; index < attributeRows.size(); index++) {
                writeRow(attributes, index + 2, attributeRows.get(index));
            }

            Sheet enums = workbook.createSheet("枚举值定义");
            writeRow(enums, 0, "枚举值定义：填写枚举型属性的候选值，前两行为模板说明与表头");
            writeRow(enums, 1, "Category_Code", "Attribute_Key", "Option_Code", "Option_Name", "Display_Label");
            for (int index = 0; index < enumRows.size(); index++) {
                writeRow(enums, index + 2, enumRows.get(index));
            }

            workbook.write(output);
            return new MockMultipartFile(
                    "file",
                    fileName,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    output.toByteArray());
        }
    }

    private void writeRow(Sheet sheet, int rowIndex, String... values) {
        Row row = sheet.createRow(rowIndex);
        for (int index = 0; index < values.length; index++) {
            row.createCell(index).setCellValue(values[index]);
        }
    }

    private String uniqueSuffix() {
        return UUID.randomUUID().toString().replace("-", "").substring(0, 8).toUpperCase();
    }

    @TestConfiguration
    static class SyncAsyncExecutorConfig {

        @Bean(name = "workbookImportTaskExecutor")
        SyncTaskExecutor workbookImportTaskExecutor() {
            return new SyncTaskExecutor();
        }
    }
}