package com.plm.attribute.version.service.workbook;

import com.plm.attribute.version.service.MetaAttributeManageService;
import com.plm.attribute.version.service.MetaAttributeQueryService;
import com.plm.attribute.version.service.MetaCategoryCrudService;
import com.plm.common.api.dto.attribute.MetaAttributeDefDetailDto;
import com.plm.common.api.dto.attribute.MetaAttributeUpsertRequestDto;
import com.plm.common.api.dto.category.CreateCategoryRequestDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportDryRunOptionsDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportDryRunResponseDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportJobStatusDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportLogEventDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportLogPageDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportStartRequestDto;
import com.plm.common.api.dto.imports.workbook.WorkbookImportStartResponseDto;
import com.plm.infrastructure.version.repository.MetaCategoryDefRepository;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.core.task.SyncTaskExecutor;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.UUID;

@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.NONE,
        properties = {
                "spring.main.lazy-initialization=true",
                "spring.main.allow-bean-definition-overriding=true"
        }
)
@ActiveProfiles("dev")
@Transactional
@Import(WorkbookImportServiceIT.SyncAsyncExecutorConfig.class)
class WorkbookImportServiceIT {

    @Autowired
    private WorkbookImportDryRunService dryRunService;

    @Autowired
    private WorkbookImportExecutionService executionService;

    @Autowired
    private WorkbookImportRuntimeService runtimeService;

    @Autowired
    private MetaCategoryCrudService categoryCrudService;

    @Autowired
    private MetaAttributeManageService attributeManageService;

    @Autowired
    private MetaAttributeQueryService attributeQueryService;

    @Autowired
    private MetaCategoryDefRepository categoryDefRepository;

    @Test
    void dryRun_shouldPreviewAutoGeneratedCategoryAttributeAndEnumCodes() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createAutoWorkbook(suffix);

        WorkbookImportDryRunResponseDto response = dryRunService.dryRun(workbook, "it-user", autoOptions());

        Assertions.assertNotNull(response.getImportSessionId());
        Assertions.assertEquals(0, response.getSummary().getErrorCount());
        Assertions.assertTrue(Boolean.TRUE.equals(response.getSummary().getCanImport()));
        Assertions.assertEquals(2, response.getChangeSummary().getCategories().getCreate());
        Assertions.assertEquals(1, response.getChangeSummary().getAttributes().getCreate());
        Assertions.assertEquals(2, response.getChangeSummary().getEnumOptions().getCreate());

        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto root = response.getPreview().getCategories().get(0);
        WorkbookImportDryRunResponseDto.CategoryPreviewItemDto child = response.getPreview().getCategories().get(1);
        WorkbookImportDryRunResponseDto.AttributePreviewItemDto attribute = response.getPreview().getAttributes().get(0);
        WorkbookImportDryRunResponseDto.EnumOptionPreviewItemDto firstEnum = response.getPreview().getEnumOptions().get(0);
        WorkbookImportDryRunResponseDto.EnumOptionPreviewItemDto secondEnum = response.getPreview().getEnumOptions().get(1);

        Assertions.assertEquals("SYSTEM_RULE_AUTO", root.getCodeMode());
        Assertions.assertTrue(root.getResolvedFinalCode().startsWith("MATERIAL-"), "actual root code=" + root.getResolvedFinalCode());
        Assertions.assertEquals("/" + root.getResolvedFinalCode(), root.getResolvedFinalPath());

        Assertions.assertEquals("SYSTEM_RULE_AUTO", child.getCodeMode());
        Assertions.assertEquals(root.getResolvedFinalPath() + "/" + child.getResolvedFinalCode(), child.getResolvedFinalPath());
        Assertions.assertTrue(child.getResolvedFinalCode().startsWith("MATERIAL-"), "actual child code=" + child.getResolvedFinalCode());

        Assertions.assertEquals(child.getResolvedFinalCode(), attribute.getCategoryCode());
        Assertions.assertEquals("SYSTEM_RULE_AUTO", attribute.getCodeMode());
        Assertions.assertTrue(attribute.getResolvedFinalCode().startsWith("ATTR-" + child.getResolvedFinalCode() + "-"),
                "actual attribute code=" + attribute.getResolvedFinalCode());

        Assertions.assertEquals(attribute.getResolvedFinalCode(), firstEnum.getAttributeKey());
        Assertions.assertEquals(attribute.getResolvedFinalCode(), secondEnum.getAttributeKey());
        Assertions.assertTrue(firstEnum.getResolvedFinalCode().startsWith("ENUM-" + attribute.getResolvedFinalCode() + "-"),
                "actual enum code=" + firstEnum.getResolvedFinalCode());
        Assertions.assertTrue(secondEnum.getResolvedFinalCode().startsWith("ENUM-" + attribute.getResolvedFinalCode() + "-"),
                "actual enum code=" + secondEnum.getResolvedFinalCode());
    }

        @Test
        void dryRun_shouldReportInvalidDataTypeWithSupportedValues() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createWorkbook(
            "workbook-invalid-type-" + suffix + ".xlsx",
            List.<String[]>of(new String[]{"MATERIAL", "TYPE-" + suffix, "/TYPE-" + suffix, "Type Category " + suffix}),
            List.<String[]>of(attributeRow("TYPE-" + suffix, "Type Category " + suffix, "ATTR-TYPE-" + suffix, "Broken Attr " + suffix, "broken" + suffix.toLowerCase(), "enum_bad")),
            List.of());

        WorkbookImportDryRunResponseDto response = dryRunService.dryRun(workbook, "it-user", manualKeepExistingOptions());

        Assertions.assertFalse(Boolean.TRUE.equals(response.getSummary().getCanImport()));
        Assertions.assertTrue(response.getSummary().getErrorCount() >= 1);
        WorkbookImportDryRunResponseDto.IssueDto issue = response.getIssues().stream()
            .filter(item -> "ATTRIBUTE_DATA_TYPE_INVALID".equals(item.getErrorCode()))
            .findFirst()
            .orElseThrow();
        Assertions.assertEquals("Data_Type", issue.getColumnName());
        Assertions.assertEquals("enum_bad", issue.getRawValue());
        Assertions.assertTrue(issue.getExpectedRule().contains("string"));
        Assertions.assertTrue(issue.getExpectedRule().contains("multi_enum"));
        }

    @Test
    void startImport_shouldPersistEntitiesAndExposeCompletedJobStatusAndLogs() throws Exception {
        String suffix = uniqueSuffix();
        MockMultipartFile workbook = createAutoWorkbook(suffix);
        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", autoOptions());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setImportSessionId(dryRun.getImportSessionId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.TRUE);

        WorkbookImportStartResponseDto start = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(start.getJobId());
        WorkbookImportLogPageDto logs = runtimeService.getLogs(start.getJobId(), null, 200, null, null, null, null);

        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals(WorkbookImportSupport.STAGE_FINALIZING, status.getCurrentStage());
        Assertions.assertEquals(100, status.getOverallPercent());
        Assertions.assertEquals(2, status.getProgress().getCategories().getCreated());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getCreated());
        Assertions.assertEquals(2, status.getProgress().getEnumOptions().getCreated());
        Assertions.assertEquals(2, status.getProgress().getCategories().getProcessed());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getProcessed());
        Assertions.assertEquals(2, status.getProgress().getEnumOptions().getProcessed());

        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_CODE_SEQUENCE_RESERVED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_CODE_SEQUENCE_RESERVED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_CODE_SEQUENCE_RESERVED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_IMPORTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_IMPORTED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_IMPORTED"));

        List<WorkbookImportLogEventDto> categoryImportedLogs = logs.getItems().stream()
            .filter(item -> "CATEGORY_IMPORTED".equals(item.getCode()))
            .toList();
        WorkbookImportLogEventDto attributeImportedLog = logs.getItems().stream()
            .filter(item -> "ATTRIBUTE_IMPORTED".equals(item.getCode()))
            .findFirst()
            .orElseThrow();
        List<WorkbookImportLogEventDto> enumImportedLogs = logs.getItems().stream()
            .filter(item -> "ENUM_OPTION_IMPORTED".equals(item.getCode()))
            .toList();

        Assertions.assertEquals(2, categoryImportedLogs.size());
        Assertions.assertEquals(2, enumImportedLogs.size());

        for (WorkbookImportLogEventDto categoryLog : categoryImportedLogs) {
            Assertions.assertTrue(categoryDefRepository.findByBusinessDomainAndCodeKey("MATERIAL", categoryLog.getEntityKey()).isPresent());
        }

        String[] attributeKeyParts = attributeImportedLog.getEntityKey().split("/");
        String actualAttributeKey = attributeKeyParts[attributeKeyParts.length - 1];
        MetaAttributeDefDetailDto detail = attributeQueryService.detail(actualAttributeKey, true);
        Assertions.assertNotNull(detail);
        Assertions.assertEquals("Color " + suffix, detail.getLatestVersion().getDisplayName());
        Assertions.assertEquals(2, detail.getLovValues().size());

        List<String> actualEnumCodes = enumImportedLogs.stream()
            .map(WorkbookImportLogEventDto::getEntityKey)
            .map(entityKey -> entityKey.substring(entityKey.lastIndexOf('/') + 1))
            .toList();
        Assertions.assertEquals(actualEnumCodes.get(0), detail.getLovValues().get(0).getCode());
        Assertions.assertEquals(actualEnumCodes.get(1), detail.getLovValues().get(1).getCode());

        WorkbookImportDryRunResponseDto.AttributePreviewItemDto attributePreview = dryRun.getPreview().getAttributes().get(0);
        Assertions.assertTrue(actualAttributeKey.startsWith("ATTR-"), "actual attribute key=" + actualAttributeKey);
        Assertions.assertTrue(attributePreview.getResolvedFinalCode().startsWith("ATTR-"), "preview attribute key=" + attributePreview.getResolvedFinalCode());
    }

    @Test
    void startImport_shouldSkipExistingRowsWhenDuplicatePolicyIsKeepExisting() throws Exception {
        String suffix = uniqueSuffix();
        String categoryCode = "KEEP-CAT-" + suffix;
        String attributeKey = "ATTR_KEEP_" + suffix;
        String enumCode = "ENUM_KEEP_" + suffix;

        createCategory(categoryCode, "Existing Category " + suffix);
        createManualEnumAttribute(categoryCode, attributeKey, enumCode, "Existing Status " + suffix, "Enabled " + suffix);

        MockMultipartFile workbook = createKeepExistingWorkbook(categoryCode, attributeKey, enumCode, suffix);
        WorkbookImportDryRunResponseDto dryRun = dryRunService.dryRun(workbook, "it-user", manualKeepExistingOptions());

        Assertions.assertTrue(Boolean.TRUE.equals(dryRun.getSummary().getCanImport()));
        Assertions.assertEquals("KEEP_EXISTING", dryRun.getPreview().getCategories().get(0).getResolvedAction());
        Assertions.assertEquals("KEEP_EXISTING", dryRun.getPreview().getAttributes().get(0).getResolvedAction());
        Assertions.assertEquals("KEEP_EXISTING", dryRun.getPreview().getEnumOptions().get(0).getResolvedAction());

        WorkbookImportStartRequestDto request = new WorkbookImportStartRequestDto();
        request.setImportSessionId(dryRun.getImportSessionId());
        request.setOperator("it-user");
        request.setAtomic(Boolean.TRUE);

        WorkbookImportStartResponseDto start = executionService.startImport(request);
        WorkbookImportJobStatusDto status = runtimeService.getJobStatus(start.getJobId());
        WorkbookImportLogPageDto logs = runtimeService.getLogs(start.getJobId(), null, 100, null, null, null, null);

        Assertions.assertEquals(WorkbookImportSupport.STATUS_COMPLETED, status.getStatus());
        Assertions.assertEquals(1, status.getProgress().getCategories().getSkipped());
        Assertions.assertEquals(1, status.getProgress().getAttributes().getSkipped());
        Assertions.assertEquals(1, status.getProgress().getEnumOptions().getSkipped());
        Assertions.assertTrue(hasLogCode(logs.getItems(), "CATEGORY_SKIPPED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ATTRIBUTE_SKIPPED"));
        Assertions.assertTrue(hasLogCode(logs.getItems(), "ENUM_OPTION_SKIPPED"));

        MetaAttributeDefDetailDto detail = attributeQueryService.detail(attributeKey, true);
        Assertions.assertEquals("Existing Status " + suffix, detail.getLatestVersion().getDisplayName());
        Assertions.assertEquals(1, detail.getLovValues().size());
        Assertions.assertEquals(enumCode, detail.getLovValues().get(0).getCode());
        Assertions.assertEquals("Enabled " + suffix, detail.getLovValues().get(0).getValue());
    }

    private WorkbookImportDryRunOptionsDto autoOptions() {
        WorkbookImportDryRunOptionsDto options = new WorkbookImportDryRunOptionsDto();
        options.getCodingOptions().setCategoryCodeMode("SYSTEM_RULE_AUTO");
        options.getCodingOptions().setAttributeCodeMode("SYSTEM_RULE_AUTO");
        options.getCodingOptions().setEnumOptionCodeMode("SYSTEM_RULE_AUTO");
        options.getDuplicateOptions().setCategoryDuplicatePolicy("FAIL_ON_DUPLICATE");
        options.getDuplicateOptions().setAttributeDuplicatePolicy("FAIL_ON_DUPLICATE");
        options.getDuplicateOptions().setEnumOptionDuplicatePolicy("FAIL_ON_DUPLICATE");
        return options;
    }

    private WorkbookImportDryRunOptionsDto manualKeepExistingOptions() {
        WorkbookImportDryRunOptionsDto options = new WorkbookImportDryRunOptionsDto();
        options.getCodingOptions().setCategoryCodeMode("EXCEL_MANUAL");
        options.getCodingOptions().setAttributeCodeMode("EXCEL_MANUAL");
        options.getCodingOptions().setEnumOptionCodeMode("EXCEL_MANUAL");
        options.getDuplicateOptions().setCategoryDuplicatePolicy("KEEP_EXISTING");
        options.getDuplicateOptions().setAttributeDuplicatePolicy("KEEP_EXISTING");
        options.getDuplicateOptions().setEnumOptionDuplicatePolicy("KEEP_EXISTING");
        return options;
    }

    private void createCategory(String code, String name) {
        CreateCategoryRequestDto request = new CreateCategoryRequestDto();
        request.setBusinessDomain("MATERIAL");
        request.setCode(code);
        request.setName(name);
        categoryCrudService.create(request, "it-user");
    }

    private void createManualEnumAttribute(String categoryCode,
                                           String attributeKey,
                                           String enumCode,
                                           String attributeName,
                                           String optionName) {
        MetaAttributeUpsertRequestDto request = new MetaAttributeUpsertRequestDto();
        request.setKey(attributeKey);
        request.setGenerationMode("MANUAL");
        request.setDisplayName(attributeName);
        request.setAttributeField("status" + uniqueSuffix().toLowerCase());
        request.setDataType("enum");
        request.setLovKey(attributeKey + "_LOV");
        request.setLovGenerationMode("MANUAL");
        request.setLovValues(List.of(lovValue(enumCode, optionName)));
        attributeManageService.create(categoryCode, request, "it-user");
    }

    private MetaAttributeUpsertRequestDto.LovValueUpsertItem lovValue(String code, String name) {
        MetaAttributeUpsertRequestDto.LovValueUpsertItem item = new MetaAttributeUpsertRequestDto.LovValueUpsertItem();
        item.setCode(code);
        item.setName(name);
        item.setLabel(name);
        return item;
    }

    private boolean hasLogCode(List<WorkbookImportLogEventDto> items, String code) {
        return items.stream().map(WorkbookImportLogEventDto::getCode).anyMatch(code::equals);
    }

    private MockMultipartFile createAutoWorkbook(String suffix) throws Exception {
        String rootCode = "ROOT-" + suffix;
        String childCode = "CHILD-" + suffix;
        String attributeCode = "ATTR-REF-" + suffix;
        return createWorkbook(
                "workbook-auto-" + suffix + ".xlsx",
            List.<String[]>of(
                        new String[]{"MATERIAL", rootCode, "/" + rootCode, "Root " + suffix},
                        new String[]{"MATERIAL", childCode, "/" + rootCode + "/" + childCode, "Child " + suffix}
                ),
            List.<String[]>of(
                        attributeRow(childCode, "Child " + suffix, attributeCode, "Color " + suffix, "color" + suffix.toLowerCase(), "enum")
                ),
            List.<String[]>of(
                        new String[]{childCode, attributeCode, "ENUM-REF-A-" + suffix, "Red " + suffix, "Red " + suffix},
                        new String[]{childCode, attributeCode, "ENUM-REF-B-" + suffix, "Blue " + suffix, "Blue " + suffix}
                )
        );
    }

    private MockMultipartFile createKeepExistingWorkbook(String categoryCode,
                                                         String attributeKey,
                                                         String enumCode,
                                                         String suffix) throws Exception {
        return createWorkbook(
                "workbook-keep-" + suffix + ".xlsx",
            List.<String[]>of(new String[]{"MATERIAL", categoryCode, "/" + categoryCode, "Workbook Category " + suffix}),
            List.<String[]>of(attributeRow(categoryCode, "Workbook Category " + suffix, attributeKey, "Workbook Status " + suffix, "status" + suffix.toLowerCase(), "enum")),
            List.<String[]>of(new String[]{categoryCode, attributeKey, enumCode, "Workbook Enabled " + suffix, "Workbook Enabled " + suffix})
        );
    }

    private String[] attributeRow(String categoryCode,
                                  String categoryName,
                                  String attributeKey,
                                  String attributeName,
                                  String attributeField,
                                  String dataType) {
        return new String[]{
                categoryCode,
                categoryName,
                attributeKey,
                attributeName,
                attributeField,
                "",
                dataType,
                "",
                "",
                "N",
                "N",
                "Y",
                "N",
                "N",
                "",
                "",
                "",
                "",
                "",
                ""
        };
    }

    private MockMultipartFile createWorkbook(String fileName,
                                             List<String[]> categoryRows,
                                             List<String[]> attributeRows,
                                             List<String[]> enumRows) throws Exception {
        try (XSSFWorkbook workbook = new XSSFWorkbook(); ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            Sheet categories = workbook.createSheet("分类层级");
            writeRow(categories, 0, "Business_Domain", "Category_Code", "Category_Path", "Category_Name");
            for (int index = 0; index < categoryRows.size(); index++) {
                writeRow(categories, index + 1, categoryRows.get(index));
            }

            Sheet attributes = workbook.createSheet("属性定义");
            writeRow(attributes, 0,
                    "Category_Code",
                    "Category_Name",
                    "Attribute_Key",
                    "Attribute_Name",
                    "Attribute_Field",
                    "Description",
                    "Data_Type",
                    "Unit",
                    "Default_Value",
                    "Required",
                    "Unique",
                    "Searchable",
                    "Hidden",
                    "Read_Only",
                    "Min_Value",
                    "Max_Value",
                    "Step",
                    "Precision",
                    "True_Label",
                    "False_Label");
            for (int index = 0; index < attributeRows.size(); index++) {
                writeRow(attributes, index + 1, attributeRows.get(index));
            }

            Sheet enums = workbook.createSheet("枚举值定义");
            writeRow(enums, 0, "Category_Code", "Attribute_Key", "Option_Code", "Option_Name", "Display_Label");
            for (int index = 0; index < enumRows.size(); index++) {
                writeRow(enums, index + 1, enumRows.get(index));
            }

            workbook.write(output);
            return new MockMultipartFile(
                    "file",
                    fileName,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    output.toByteArray());
        }
    }

    private void writeRow(Sheet sheet, int rowIndex, String... values) {
        Row row = sheet.createRow(rowIndex);
        for (int index = 0; index < values.length; index++) {
            row.createCell(index).setCellValue(values[index]);
        }
    }

    private String uniqueSuffix() {
        return UUID.randomUUID().toString().replace("-", "").substring(0, 8).toUpperCase();
    }

    @TestConfiguration
    static class SyncAsyncExecutorConfig {

        @Bean(name = "workbookImportTaskExecutor")
        SyncTaskExecutor workbookImportTaskExecutor() {
            return new SyncTaskExecutor();
        }
    }
}